### ISSUE TITLE
UT-HAR dataset segmentation window

### ISSUE THREAD

**Issue by linkmode** [CHENXINYAN-sg/WiFi-CSI-Sensing-Benchmark#11]
Does the UT-HAR dataset use a sliding window for segmentation, and what are the window lengths and sliding steps?

**Comment by Marsrocky** [comment]
Yes it is divided by a sliding window so that the samples are generated. The hyperparameter is written in the paper and appendix.

**Comment by Marsrocky** [comment]
I apologize that I also forgot the window length. The total number is around 5000 samples, and the window length follows the paper https://ojs.aaai.org/index.php/AAAI/article/view/16103
