### ISSUE TITLE
Inquiry on Running Machine Learning Models on a Specific Dataset

### ISSUE THREAD

**Issue by izzrishabh** [CHENXINYAN-sg/WiFi-CSI-Sensing-Benchmark#15]
Dear Authors,

I am currently working with the machine learning models provided in your repository and would like to inquire if it is possible to run the models on a single, specific dataset rather than loading all the required dataset files as outlined in the repository.

Due to storage limitations and specific use-case needs, I am interested in streamlining the process to focus on one particular dataset. Could you please advise on how to modify the code or workflow to accommodate this?

Thankyou for your assistance.

Best Regards.

**Comment by xyanchen** [comment]
Hi,

As described in the repo, you could choose any single dataset from the available four datasets for model training by passing dataset name parameter in the command line.

But if you want to traing the models on your own dataset, you will need to define your dataloader following the format in [dataset.py](https://github.com/xyanchen/WiFi-CSI-Sensing-Benchmark/blob/main/dataset.py).

Hope this solves your question.

Best.

**Comment by izzrishabh** [comment]
Dear Authors, 
I hope you are doing well, I am currently working with the UT_HAR dataset from this repository, but I am encountering an issue. The dataset files seem to be corrupted and are not opening properly. I have tried opening them multiple times and with different tools, but I have been unsuccessful.

Could you please help me by providing replacement files or guidance on how to access functional versions of the datasets? If there are alternate methods or updates regarding these files, I would greatly appreciate your help.

Thank you very much for your attention to this matter.
 I am attaching some error screenshots for your reference.
 
![Error](https://github.com/user-attachments/assets/378cc277-c7b3-455d-adcf-e45cf1fea137)
![Error2](https://github.com/user-attachments/assets/f457bdc0-5e3e-4324-89e0-b38168e6f28e)

**Comment by xyanchen** [comment]
Hi, you need to

**Comment by xyanchen** [comment]
Hi, you need to read the UT_HAR data with the following code, which is written in dataset.py file:

**Comment by xyanchen** [comment]
Hi, you need to read the UT_HAR data with the following code, which is written in dataset.py file:

with open(data_dir, 'rb') as f:
&nbsp;&nbsp;&nbsp;&nbsp;     data = np.load(f)
