### ISSUE TITLE
为什么用github上的程序和google上的数据跑，准确率和sensefi论文中的不一样呢？

### ISSUE THREAD

**Issue by TianChaojie155038** [CHENXINYAN-sg/WiFi-CSI-Sensing-Benchmark#17]
Widar和NTU-Fi都是跑几轮acc都达到100%了，但是论文里不是这样，请问这是出了啥问题？
![Widardata](https://github.com/user-attachments/assets/b2e2c701-33be-4d09-8678-142654148cbe)

![NTU_Fi](https://github.com/user-attachments/assets/32ce548b-8b8a-4a00-a266-1d5505daa3d7)

**Comment by zjh-0811** [comment]
我也遇到了此类问题，请问您解决了吗

**Comment by TianChaojie155038** [comment]
> 我也遇到了此类问题，请问您解决了吗
还没

**Comment by zjh-0811** [comment]
你其他的数据集跑起来怎么样，我为啥所有的一跑起来，第二轮准确率就为1了

**Comment by TianChaojie155038** [comment]
> 你其他的数据集跑起来怎么样，我为啥所有的一跑起来，第二轮准确率就为1了
我跑UT-HAR是和论文里面的结果一致的，NTU-Fi两个数据集和Widar的都为1，请见图
![NTU-Fi_HAR](https://github.com/user-attachments/assets/3fa8cb69-c5bf-4f8a-a642-fc4438174f76)
![UT_HAR](https://github.com/user-attachments/assets/1975977d-1f90-4d81-a67a-e361c2731795)
![Widar](https://github.com/user-attachments/assets/9efb143c-9498-4c5f-b821-af09dc34c943)

**Comment by zjh-0811** [comment]
你的数据集是自己下载的，还是从他的链接里下载的？他提供的四个数据集我都是跑到第二轮就为1了，目前还不知道是什么问题。你有没有修改他的代码？

**Comment by TianChaojie155038** [comment]
> 你的数据集是自己下载的，还是从他的链接里下载的？他提供的四个数据集我都是跑到第二轮就为1了，目前还不知道是什么问题。你有没有修改他的代码？

我的四个数据集都是从他的链接里下载的；程序是GitHub上的那个，程序直接下载下来后，两个NTU数据集和Widar数据集都能直接跑起来，但是准确率在第二轮时会变为1；UT_HAR是不能直接跑起来的，他的代码里有个bug，需要自己改一下，但是UT_HAR跑起来后和他的论文里的结果是一致的

**Comment by zjh-0811** [comment]
那个bug是啥能分享下吗

**Comment by TianChaojie155038** [comment]
> 那个bug是啥能分享下吗

util.py文件里第13行和第14行代码有问题，会报keyerror，找到字典里的正确键然后改正就可以了。

**Comment by TianChaojie155038** [comment]
> 那个bug是啥能分享下吗

util.py文件里第13行和第14行代码有问题，会报keyerror，找到字典里的正确键然后改正就可以了。

**Comment by TianChaojie155038** [comment]
对于准确率变为1的问题，应该是划分数据集的程序没能正确读取到标签导致的

**Comment by zjh-0811** [comment]
你解决了吗

**Comment by zjh-0811** [comment]
准确率变为1的问题

**Comment by TianChaojie155038** [comment]
> 你解决了吗
划分数据集的程序没能正确读取到标签导致的，应该是这个问题

**Comment by TianChaojie155038** [comment]
> 你解决了吗

划分数据集的程序没能正确读取到标签导致的，应该是这个问题

**Comment by fenghaojin** [comment]
> > 你解决了吗
> 
> 划分数据集的程序没能正确读取到标签导致的，应该是这个问题

请问您在训练Widar数据集时是否出现训练过慢的问题？我这里一轮要好久，显卡利用率很低

**Comment by TianChaojie155038** [comment]
> > > 你解决了吗
> > 
> > 
> > 划分数据集的程序没能正确读取到标签导致的，应该是这个问题
> 
> 请问您在训练Widar数据集时是否出现训练过慢的问题？我这里一轮要好久，显卡利用率很低

是挺慢的，样本数太大了

**Comment by hsin1219** [comment]
> > 你的数据集是自己下载的，还是从他的链接里下载的？他提供的四个数据集我都是跑到第二轮就为1了，目前还不知道是什么问题。你有没有修改他的代码？
> 
> 我的四个数据集都是从他的链接里下载的；程序是GitHub上的那个，程序直接下载下来后，两个NTU数据集和Widar数据集都能直接跑起来，但是准确率在第二轮时会变为1；UT_HAR是不能直接跑起来的，他的代码里有个bug，需要自己改一下，但是UT_HAR跑起来后和他的论文里的结果是一致的

想詢問一下BUG要如何修正成正確的詞 查找不到

**Comment by Archerer** [comment]
请问你数据集是直接在windows下载的，还是在Linux环境下载的？

**Comment by TianChaojie155038** [comment]
官方程序是linux环境的，如果你用的是windows的话，把里面的正斜杠换成反斜杠就行，改完这个应该就能解决你在windows上遇到的问题

**Comment by Archerer** [comment]
> 官方程序是linux环境的，如果你用的是windows的话，把里面的正斜杠换成反斜杠就行，改完这个应该就能解决你在windows上遇到的问题

感谢，确实是路径上的问题

**Comment by Marsrocky** [comment]
是系统问题，因为Linux和Windows的斜杠是反的，我们readme里注明了系统的问题，默认是linux。
